### ISSUE TITLE
.ttl file to load ontology from github

### ISSUE THREAD

**Issue by RoteKekse** [emmo-repo/domain-photovoltaics#19]
Hey Casper,

I talked to Simon about this and he said I can ask you. Is it possible to have a .ttl file which loads the current version of the ontology from the github development branch.

The reason is that then by just opening this file people can browse the ontology without the need of downloading/pulling the recent updates.

Best Micha

**Comment by CasperWA** [comment]
Sure, this can be done by editing the `catalog-v001.xml` file. I can create a commented out line. One would then have to manually change the commentation lines in this file to be able to fetch the Turtle files from the desired location (locally or from GitHub).

**Comment by RoteKekse** [comment]
Hey Casper, thanks for the response. I am not sure if I understand. Can one open the ```catalog-v001.xml``` file with protege? I am not sure about the role of this file.

If you can provide such an .xml file, this would be great.

Thank you
Best Micha

**Comment by CasperWA** [comment]
So to understand completely. You wish to have a file you can pass around that will automatically load the ontologies from GitHub? Or do you wish to have a URL you can use in Protégé that will ensure everything is loaded correctly there?

**Comment by RoteKekse** [comment]
I think a file is perfect. You open it with protege and it displays the current state of the ontology for review. I think this is easiert to handle. Thanks I will have a look :)

**Comment by CasperWA** [comment]
> I think a file is perfect. You open it with protege and it displays the current state of the ontology for review. I think this is easiert to handle. Thanks I will have a look :)

Excellent. I have opened a PR for it #20. I have written some instructions to follow to try it out in the PR description. When you have done so, please let me know in the PR and I will then add a section to the README as well as update the file properly to point to the branch that makes most sense for you. Whether that should be `main` or `development`.

**Comment by RoteKekse** [comment]
Hey, great, i tested it :) it should point to development. 

Thank you for your help.

**Comment by CasperWA** [comment]
The [`development`](https://github.com/emmo-repo/domain-photovoltaics/tree/development) branch has now been successfully updated.
To see the updated README when one first goes to the repository, the README in the `main` branch must be updated accordingly.
